### ISSUE TITLE
[kibana] Optional  load dashboards and templates on startup image

### ISSUE THREAD

**Issue by marcuslacerda** [cit-witix/witix-docker#2]
Exemplo:

```
witix-kibana:
    build: kibana/
    volumes:
        **- ./dashboards/:/opt/kibana/dashboards
        - ./templates/:/opt/kibana/templates**
```
